// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using spaceTracker.Data;

#nullable disable

namespace spaceTracker.Migrations
{
    [DbContext(typeof(SpaceTrackerDbContext))]
    [Migration("20251105173648_AddAstronautEntity")]
    partial class AddAstronautEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("spaceTracker.Data.Entities.AstronautEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgencyJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("agency_json");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_death");

                    b.Property<DateTime?>("FirstFlight")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_flight");

                    b.Property<int>("FlightsCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flights_count");

                    b.Property<string>("ImageJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_json");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT")
                        .HasColumnName("instagram");

                    b.Property<int>("LandingsCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("landings_count");

                    b.Property<DateTime?>("LastFlight")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_flight");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NationalityJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("nationality_json");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_image");

                    b.Property<string>("ProfileImageThumbnail")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_image_thumbnail");

                    b.Property<int>("SpacewalksCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("spacewalks_count");

                    b.Property<string>("StatusJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("status_json");

                    b.Property<string>("TimeInSpace")
                        .HasColumnType("TEXT")
                        .HasColumnName("time_in_space");

                    b.Property<string>("Twitter")
                        .HasColumnType("TEXT")
                        .HasColumnName("twitter");

                    b.Property<string>("TypeJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("type_json");

                    b.Property<string>("Wiki")
                        .HasColumnType("TEXT")
                        .HasColumnName("wiki");

                    b.HasKey("Id");

                    b.ToTable("astronauts", (string)null);
                });

            modelBuilder.Entity("spaceTracker.Data.Entities.SpaceProgramEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgenciesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("agencies_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("ImageJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_json");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("space_programs", (string)null);
                });

            modelBuilder.Entity("spaceTracker.Data.Entities.SpacecraftEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImageJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_json");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.ToTable("spacecraft", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
